### ISSUE TITLE
yeti lacks let rec

### ISSUE THREAD

**Issue by jordanblack** [mth/yeti#19]
yeti lacks let rec equivalent

> a = [do (): length a done]
1:20: Unknown identifier: a

**Comment by mth** [comment]
I'm actually a bit impressed that the equivalent works in OCaml.

    # let rec a = [fun () -> List.length a];;
    val a : (unit -> int) list = [<fun>]
    # List.hd a ();;
    - : int = 1

Yeti makes recursive binding only for lambdas, which is usually the useful thing to do and pretty simple rule. It would be possible to make the rule to be "make always a recursive binding, but hide it outside of lambdas", which would solve this case nicely, but it is more complex rule and may cause mistakes with unintentional recursive bindings.

IMHO this is also needed too rarely to justify adding new keyword and complicating the compilers code generation with non-function recursive closures needed by this. I would suggest using a work-around. Simplest one is using mutable variable (downside is possible polymorphism restrictions).

    var a = [];
    a := [do (): length a done];

Alternative is just wrapping the value into lambda, which would give the recursive binding.

    a = \[do (): length (a ()) done];
    a = a ();

Yeti type inferencer is pretty good at retaining polymorphism on application, so this should be better on this regard.
