### ISSUE TITLE
build script downloading asm library over http with no checksum or signing is a security hazard

### ISSUE THREAD

**Issue by jordanblack** [mth/yeti#20]
The ant build script downloading asm library over http with no checksum or signing is a security hazard opening the user to a man in the middle attack. Same thing with the main yeti web site (but git over https is a workaround if the user knows and cares).

**Comment by mth** [comment]
The build script now does checksum verification: https://github.com/mth/yeti/commit/d6953800a0336113fda0f014ce86920ea1e748e1

The checksums should be added to the release jar links also, so these could be verified, but that's not yet done.
